module.exports = {
  items: require('./items/getItems'),
  adminItems: require('./admin/adminGetItems'),
  adminEditItems: require('./admin/adminEditItems'),
  adminUsers: require('./admin/adminGetUsers'),
  adminTrans: require('./admin/adminGetTrans'),
  adminOrder: require('./admin/adminGetOrder'),
  cancelOrder: require('./admin/cancelOrder'),
  signup: require('./users/signup'),
  signin: require('./users/signin'),
  refreshToken: require('./users/refreshTokenRequest'),
  getUserInfo: require('./users/getUserInfo'),
  editUserInfo: require('./users/editUserInfo'),
  withdrawal: require('./users/withdrawal'),
  getCartItems: require('./cart/getCartItems'),
  combineCartItems: require('./cart/combineCartItems'),
  trackQuant: require('./cart/trackQuant'),
  addToCart: require('./cart/addToCart'),
  removeFromCart: require('./cart/removeFromCart'),
  changeQuant: require('./cart/changeQuant'),
  getOrders: require('./orders/getOrders'),
  makeOrder: require('./orders/makeOrder'),
  cancelRequest: require('./orders/cancelRequest')
};
